stages:
  - trigger
  - deploy

trigger-PatientsData:
  stage: trigger
  trigger:
    include: k8s/PatientsData/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/PatientsData/**/*

trigger-Doctors:
  stage: trigger
  trigger:
    include: k8s/Doctors/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/Doctors/**/*
        
trigger-AppointmentsData:
  stage: trigger
  trigger:
    include: k8s/AppointmentsData/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/AppointmentsData/**/*

trigger-DoctorsApplicationMicroservice:
  stage: trigger
  trigger:
    include: k8s/DoctorsApplicationMicroservice/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/DoctorsApplicationMicroservice/**/*
        
trigger-PatientsApplicationMicroservice:
  stage: trigger
  trigger:
    include: k8s/PatientsApplicationMicroservice/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/PatientsApplicationMicroservice/**/*

trigger-PatientWebApp:
  stage: trigger
  trigger:
    include: k8s/PatientWebApp/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/PatientWebApp/**/*



