stages:
  - trigger
  - deploy

trigger-PatientsData:
  stage: trigger
  trigger:
    include: k8s/PatientsData/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/PatientsData/**/*

trigger-AppointmentsData:
  stage: trigger
  trigger:
    include: k8s/AppointmentsData/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/AppointmentsData/**/*

trigger-DoctorsApplicationMicroservice:
  stage: trigger
  trigger:
    include: k8s/DoctorsApplicationMicroservice/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/DoctorsApplicationMicroservice/**/*

trigger-PatientWebApp:
  stage: trigger
  trigger:
    include: k8s/PatientWebApp/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - k8s/PatientWebApp/**/*

deploy:
  stage: deploy
  tags:
    - all
  only:
    - master
  script:
    - echo "test"

