version: "3.3"

networks:
  int_network:

services:
  patients-data:
    image: shaggy17goo/uaim:patients_data
    ports:
      - "8081:80"
    networks:
      - int_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
  appointments-data:
    image: shaggy17goo/uaim:appointments_data
    ports:
      - "8082:80"
    networks:
      - int_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
  doctors-data:
    image: shaggy17goo/uaim:doctors_data
    ports:
      - "8083:80"
    networks:
      - int_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
  patient-microservice:
    image: shaggy17goo/uaim:patient_microservice
    environment:
     - DOCTORS_HOST=http://doctors-data:80/
     - PATIENTS_HOST=http://patients-data:80/
     - APPOINTMENTS_HOST=http://appointments-data:80/
    ports:
      - "8084:80"
    networks:
      - int_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - patients-data
      - appointments-data
      - doctors-data
  
    
  doctor-microservice:
    image: shaggy17goo/uaim:doctor_microservice
    environment:
     - DOCTORS_HOST=http://doctors-data:80/
     - PATIENTS_HOST=http://patients-data:80/
     - APPOINTMENTS_HOST=http://appointments-data:80/
    ports:
      - "8085:80"
    networks:
      - int_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - patients-data
      - appointments-data
      - doctors-data
      
  patient-web-app:
    image: shaggy17goo/uaim:patient_webapp
    environment:
     - SERVICE_HOST=patient-microservice
     - SERVICE_PORT=80
    ports:
      - "8086:80"
    networks:
      - int_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - patients-data
      - appointments-data
      - doctors-data


