apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-data
  labels:
    app: doctors-data
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors-data
  template:
    metadata:
      labels:
        app: doctors-data
        tier: dataservice
    spec:
      containers:
      - name: doctors-data
        image: shaggy17goo/uaim:doctors_data
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-datarest
  labels:
    app: doctors-datarest
    tier: dataservice
spec:
  selector:
    app: doctors-data
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-data
  labels:
    app: appointments-data
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments-data
  template:
    metadata:
      labels:
        app: appointments-data
        tier: dataservice
    spec:
      containers:
      - name: appointments-data
        image: shaggy17goo/uaim:appointments_data
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-datarest
  labels:
    app: appointments-datarest
    tier: dataservice
spec:
  selector:
    app: appointments-data
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-data
  labels:
    app: patients-data
    tier: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-data
  template:
    metadata:
      labels:
        app: patients-data
        tier: dataservice
    spec:
      containers:
      - name: patients-data
        image: shaggy17goo/uaim:patients_data
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: patients-datarest
  labels:
    app: patients-datarest
    tier: dataservice
spec:
  selector:
    app: doctors-data
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-microservice
  labels:
    app: patient-microservice
    tier: appservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient-microservice
  template:
    metadata:
      labels:
        app: patient-microservice
        tier: backend
    spec:
      containers:
      - name: patient-microservice
        image: shaggy17goo/uaim:patient_microservice
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        env:
            - name: DOCTORS_HOST
              value: http://doctors-datarest:80/
            - name: PATIENTS_HOST
              value: http://patients-datarest:80/
            - name: APPOINTMENTS_HOST
              value: http://appointments-datarest:80/
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: patient-microservicerest
  labels:
    app: patient-microservicerest
    tier: appservice
spec:
  selector:
    app: patient-microservice
  type: NodePort
  ports:
  - port: 80
    nodePort: 30081
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-microservice
  labels:
    app: doctor-microservice
    tier: appservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctor-microservice
  template:
    metadata:
      labels:
        app: doctor-microservice
        tier: backend
    spec:
      containers:
      - name: doctor-microservice
        image: shaggy17goo/uaim:doctor_microservice
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        env:
            - name: DOCTORS_HOST
              value: http://doctors-datarest:80/
            - name: PATIENTS_HOST
              value: http://patients-datarest:80/
            - name: APPOINTMENTS_HOST
              value: http://appointments-datarest:80/
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-microservicerest
  labels:
    app: doctor-microservicerest
    tier: appservice
spec:
  selector:
    app: doctor-microservice
  type: NodePort
  ports:
  - port: 80
    nodePort: 30082
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-web-app  
  labels:
    app: patient-web-app
    tier: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-web-app
  template:
    metadata:
      labels:
        app: patient-web-app
        tier: webapp
    spec:
      containers:
      - name: patient-web-app
        image: shaggy17goo/uaim:patient_webapp
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        env:
            - name: SERVICE_HOST
              value: patient-microservicerest
            - name: SERVICE_PORT
              value: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: patient-web-apprest
  labels:
    app: patient-web-apprest
    tier: webapp
spec:
  selector:
    app: patient-web-app
  type: NodePort
  ports:
  - port: 80
    nodePort: 30083

