apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-web-app  
  labels:
    app: patient-web-app
    tier: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-web-app
  template:
    metadata:
      labels:
        app: patient-web-app
        tier: webapp
    spec:
      containers:
      - name: patient-web-app
        image: shaggy17goo/uaim:patient_webapp
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        env:
            - name: SERVICE_HOST
              value: patient-microservicerest
            - name: SERVICE_PORT
              value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: patient-web-apprest
  labels:
    app: patient-web-apprest
    tier: webapp
spec:
  selector:
    app: patient-web-app
  type: NodePort
  ports:
  - port: 80
    nodePort: 30083

